[package]
name = "abstract-cw-plus-interface"
version = "1.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.4.1"
cw-orch = { workspace = true }
abstract-cw1 = { path = "../cw1" }
abstract-cw1-subkeys = { path = "../../contracts/cw1-subkeys" }
abstract-cw1-whitelist = { path = "../../contracts/cw1-whitelist" }
abstract-cw20-base = { path = "../../contracts/cw20-base" }
abstract-cw20-ics20 = { path = "../../contracts/cw20-ics20" }
abstract-cw3-fixed-multisig = { path = "../../contracts/cw3-fixed-multisig" }
abstract-cw3-flex-multisig = { path = "../../contracts/cw3-flex-multisig" }
abstract-cw4-group = { path = "../../contracts/cw4-group" }
abstract-cw4-stake = { path = "../../contracts/cw4-stake" }
