[package]
name = "abstract-cw-plus-interface"
version = "4.0.0"
edition = "2021"
description = "CW4 implementation of group based on staked tokens"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
library = [
  "cw1-subkeys/library",
  "cw1-whitelist/library",
  "cw20-base/library",
  "cw20-ics20/library",
  "cw3-fixed-multisig/library",
  "cw3-flex-multisig/library",
  "cw4-group/library",
  "cw4-stake/library",
]


[dependencies]
cosmwasm-std = { version = "2.0.0" }
cw-utils = { version = "2.0.0" }
cosmwasm-schema = { version = "2.0.0" }
cw-controllers = { version = "2.0.0" }
cw1 = { version = "2.0.0" }
cw1-subkeys = { version = "2.0.0" }
cw1-whitelist = { version = "2.0.0" }
cw3 = { version = "2.0.0" }
cw3-fixed-multisig = { version = "2.0.0" }
cw3-flex-multisig = { version = "2.0.0" }
cw4 = { version = "2.0.0" }
cw4-group = { version = "2.0.0" }
cw4-stake = { version = "2.0.0" }
cw20 = { version = "2.0.0" }
cw20-base = { version = "2.0.0" }
cw20-ics20 = { version = "2.0.0" }

cw-orch = { version = "0.25.0" }
from_interface_derive = { version = "0.1.0", path = "../from_interface_derive" }

[dev-dependencies]
cw-orch-interchain = { version = "0.4.0" }
