[package]
name = "abstract-cw-plus-interface"
version = "2.0.1"
edition = "2021"
description = "CW4 implementation of group based on staked tokens"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
library = [
    "abstract-cw1-subkeys/library",
    "abstract-cw1-whitelist/library",
    "abstract-cw20-base/library",
    "abstract-cw20-ics20/library",
    "abstract-cw3-fixed-multisig/library",
    "abstract-cw3-flex-multisig/library",
    "abstract-cw4-group/library",
    "abstract-cw4-stake/library",
]


[dependencies]
cosmwasm-std = "1.4.1"
cw-orch = { workspace = true }
abstract-cw1 = { version = "1.2.2", path = "../cw1" }
abstract-cw1-subkeys = { version = "2.0.0", path = "../../contracts/cw1-subkeys" }
abstract-cw1-whitelist = { version = "2.0.0", path = "../../contracts/cw1-whitelist" }
abstract-cw20-base = { version = "2.0.0", path = "../../contracts/cw20-base" }
abstract-cw20-ics20 = { version = "2.0.0", path = "../../contracts/cw20-ics20" }
abstract-cw3-fixed-multisig = { version = "2.0.0", path = "../../contracts/cw3-fixed-multisig" }
abstract-cw3-flex-multisig = { version = "2.0.0", path = "../../contracts/cw3-flex-multisig" }
abstract-cw4-group = { version = "2.0.0", path = "../../contracts/cw4-group" }
abstract-cw4-stake = { version = "2.0.0", path = "../../contracts/cw4-stake" }
