[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.cw1-subkeys]
codegen-units = 1
incremental = false

[profile.release.package.cw1-whitelist]
codegen-units = 1
incremental = false

[profile.release.package.cw3-fixed-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw3-flex-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw4-group]
codegen-units = 1
incremental = false

[profile.release.package.cw4-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw20-base]
codegen-units = 1
incremental = false

[profile.release.package.cw20-ics20]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false


[workspace.dependencies]
cw-multi-test = { version = "0.16.0" }

[patch.crates-io]
#boot-core = { git="https://github.com/Kayanski/BOOT.git", branch="feature/new-contract-interface"  }
boot-core = { path="../boot/boot-core" }
boot-contract-derive = { path="../boot/packages/boot-contract-derive"  }
boot-fns-derive = { path="../boot/packages/boot-fns-derive" }
