[package]
name = "cw1"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Definition and types for the CosmWasm-1 interface"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[features]
script = ["boot-contract-derive/outside_contract","boot-fns-derive/outside_contract", "dep:boot-core"]

[dependencies]

cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

boot-fns-derive = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface" }
boot-contract-derive = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface" }
boot-core = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface", optional=true }
