[package]
name = "cw3"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "CosmWasm-3 Interface: On-Chain MultiSig/Voting contracts"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[features]
script = ["boot-contract-derive/outside_contract","boot-fns-derive/outside_contract", "dep:boot-core"]

[dependencies]

boot-fns-derive = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface" }
boot-contract-derive = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface" }
boot-core = { git = "https://github.com/Kayanski/BOOT", branch = "feature/new-contract-interface", optional=true }
cw-utils = "1.0.1"
cw20 = { path = "../../packages/cw20", version = "1.0.1" }
cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
